#!/usr/bin/env python2

"""
Usage: %s CONSTRAINTS-QUERY-FILE VIEWS-QUERY-FILE

Reads two query files and produces an query and prints to standard output a new
query with the constraints of the first input file and the views of the second.
"""

import sys
import json

if __name__ == '__main__':
  import getopt

  try:
    opts, args = getopt.getopt(sys.argv[1:], "")
    if len(args) != 2:
      raise getopt.GetoptError("wrong number of positional arguments")
    opts = dict(opts)
  except getopt.GetoptError:
    print >> sys.stderr, __doc__.strip('\n\r') % (sys.argv[0])
    sys.exit(1)

  constraints_path, views_path = args[0:2]

  with open(constraints_path) as input_file:
    constraints_query = json.load(input_file)
  with open(views_path) as input_file:
    views_query = json.load(input_file)

  new_query = { 'constraints': constraints_query['constraints'], 'views': views_query['views'] }
  json.dump(new_query, sys.stdout, sort_keys=True, indent=4)
