#!/usr/bin/env python2

"""
Usage: %s [DIFF-FILE]

Checks if a diff file is likely to indicate only differences of ordering rather
than differences in content included.
"""

import sys
import re

quoted_num_re = re.compile("^(.* )\"(-?[0-9.]+)\"(,?)")

def normline(line):
  line = line[1:].strip()
  match = quoted_num_re.match(line)
  if match is not None:
    line = "%s%s%s" % (match.group(1), match.group(2), match.group(3))
  return line

if __name__ == '__main__':
  import getopt

  try:
    opts, args = getopt.getopt(sys.argv[1:], "")
    if len(args) not in [0, 1]:
      raise getopt.GetoptError("wrong number of positional arguments")
    opts = dict(opts)
  except getopt.GetoptError:
    print >> sys.stderr, __doc__.strip('\n\r') % (sys.argv[0])
    sys.exit(1)

  input = sys.stdin if len(args) == 0 else open(args[0])

  removed = set()
  added = set()
  for line in input:
    if line.startswith('<'):
      removed.add(normline(line))
    elif line.startswith('>'):
      added.add(normline(line))

  all = removed | added
  somediff = False
  for line in all:
    if line in removed and line not in added:
      print "< %s" % (line)
      somediff = True
    elif line not in removed and line in added:
      print "> %s" % (line)
      somediff = True

  sys.exit(1 if somediff else 0)
