#!/usr/bin/env python2

"""
Usage: %s [DIFF-FILE]

Checks if a diff file is likely to indicate only differences of ordering rather
than differences in content included.
"""

import sys
import re
import collections

quoted_num_re = re.compile("\"(-?[0-9.]+)\"")

def normline(line):
  line = line[1:].strip()
  match = quoted_num_re.match(line)
  line = quoted_num_re.sub(lambda m: m.group(1), line)
  return line

if __name__ == '__main__':
  import getopt

  try:
    opts, args = getopt.getopt(sys.argv[1:], "")
    if len(args) not in [0, 1]:
      raise getopt.GetoptError("wrong number of positional arguments")
    opts = dict(opts)
  except getopt.GetoptError:
    print >> sys.stderr, __doc__.strip('\n\r') % (sys.argv[0])
    sys.exit(1)

  input = sys.stdin if len(args) == 0 else open(args[0])

  removed = collections.defaultdict(int)
  added = collections.defaultdict(int)
  for line in input:
    if line.startswith('<'):
      removed[normline(line)] += 1
    elif line.startswith('>'):
      added[normline(line)] += 1

  all = set(removed.iterkeys()) | set(added.iterkeys())
  somediff = False
  for line in all:
    d = removed[line] - added[line]
    if d != 0:
      somediff = True
      if d > 0:
        s = "<"
      else:
        s = ">"
        d = -d
      for i in range(d):
        print "%s %s" % (s, line)

  sys.exit(1 if somediff else 0)
