FROM ubuntu:14.04
MAINTAINER Andrei Vacariu <andrei@avacariu.me>
EXPOSE 1500

# MAINTAIN THE SAME ORDER OF USER CREATION BETWEEN ALL DOCKERFILES SO THAT THEY
# ALL END UP WITH THE SAME UID/GID
RUN groupadd -r lensing \
  && useradd -r -s /bin/false -g lensing lensing

ENV DEBIAN_FRONTEND noninteractive

RUN sed -i 's/archive\.ubuntu\.com/mirror.its.sfu.ca\/mirror/' /etc/apt/sources.list

RUN apt-get update && apt-get install -y build-essential python2.7 python2.7-dev python-pip libatlas-dev libatlas3-base libatlas-base-dev gfortran
RUN pip install whoosh numpy scipy scikit-learn nltk
RUN python2.7 -c 'import nltk; nltk.download("all")'

ADD . /opt/lensing

RUN cd /opt/lensing && make

CMD rm -r /build/fullData.index || \
        /opt/lensing/build/buildindex /build/fullData.index /build/fullData.json && \
        /opt/lensing/build/cluster /build/fullData.index && \
        /opt/lensing/build/tsne /build/fullData.index
