#!/usr/bin/env python2

"""
Usage: %s DOMAIN [...]

Arguments:
DOMAIN [...]  The domains to look at.

Prints metadata about one or more SimpleDB domains.
"""

import sys
import json
import boto

metadata_keys = ['domain', 'timestamp', 'item_count', 'item_names_size', 'attr_name_count', 'attr_names_size', 'attr_value_count', 'attr_values_size']

if __name__ == '__main__':
  import getopt

  try:
    opts, args = getopt.getopt(sys.argv[1:], "")
    if len(args) < 1:
      raise getopt.GetoptError("wrong number of positional arguments")
    opts = dict(opts)
  except getopt.GetoptError:
    print >> sys.stderr, __doc__.strip('\n\r') % (sys.argv[0])
    sys.exit(1)

  sdb = boto.connect_sdb()

  for dom_name in args:
    print >> sys.stderr, dom_name
    dom = sdb.get_domain(dom_name)
    md = dom.get_metadata()
    for key in metadata_keys:
      print "%s : %s" % (key, str(getattr(md, key)))
