#!/usr/bin/env python2

"""
Usage: %s

Prints the names of all SimpleDB domains.
"""

import sys
import boto

if __name__ == '__main__':
  import getopt

  try:
    opts, args = getopt.getopt(sys.argv[1:], "")
    if len(args) not in [0]:
      raise getopt.GetoptError("wrong number of positional arguments")
    opts = dict(opts)
  except getopt.GetoptError:
    print >> sys.stderr, __doc__.strip('\n\r') % (sys.argv[0])
    sys.exit(1)

  sdb = boto.connect_sdb()

  next_token = None
  while True:
    rs = sdb.get_all_domains()
    for dom in rs:
      print dom.name
    next_token = rs.next_token
    if next_token is None:
      break
