#!/usr/bin/env python2

"""
Usage: %s DOMAIN

Arguments:
DOMAIN  The domain to remove.

Removes a whole SimpleDB domain. Use with caution.
"""

import sys
import json
import boto

if __name__ == '__main__':
  import getopt

  try:
    opts, args = getopt.getopt(sys.argv[1:], "")
    if len(args) not in [1]:
      raise getopt.GetoptError("wrong number of positional arguments")
    opts = dict(opts)
  except getopt.GetoptError:
    print >> sys.stderr, __doc__.strip('\n\r') % (sys.argv[0])
    sys.exit(1)

  dom_name = args[0]

  sdb = boto.connect_sdb()
  sdb.delete_domain(dom_name)
