#!/usr/bin/env python2

"""
Usage: %s DOMAIN [...]

Arguments:
DOMAIN [...]  The domains to remove.

Removes one or more SimpleDB domains.
"""

import sys
import boto

if __name__ == '__main__':
  import getopt

  try:
    opts, args = getopt.getopt(sys.argv[1:], "")
    if len(args) < 1:
      raise getopt.GetoptError("wrong number of positional arguments")
    opts = dict(opts)
  except getopt.GetoptError:
    print >> sys.stderr, __doc__.strip('\n\r') % (sys.argv[0])
    sys.exit(1)

  sdb = boto.connect_sdb()

  for dom_name in args:
    print >> sys.stderr, dom_name
    sdb.delete_domain(dom_name)
