#!/usr/bin/env python2

"""
Usage: %s [opts] DATA-DOMAIN [DATA-FILE]

Arguments:
DATA-DOMAIN   SimpleDB domain to upload the data to.
DATA-FILE     Local data file. Uses standard input if not given.

Options:
  -d      Delete and replace the existing domain, if there is one.
  -i INT  Event ID index offset.
  -y INTS Range of valid years (negatives being BCE dates) for padding year
    values. Colon separated.

Uploads events from local data to a SimpleDB database.

Events are identified with sequential indices. Be careful to get them right if
doing multiple uploads to the same domain without deleting or clearing it first.
"""

import sys
import re
import json
import cgi
import boto
import dates

max_sdb_value_len = 1000 # should be 1024 - 1 (for the ellipsis) but seems to need some padding
base_wikipedia_url = "https://en.wikipedia.org"

ref_re = re.compile("\[[0-9]+\]")
def make_html_description(text, urls):
  def parse(url_rep):
    try:
      i = url_rep.index(' ')
      return cgi.escape(url_rep[i+1:]), url_rep[:i]
    except ValueError:
      print >> sys.stderr, "warning: couldn't understand URL replacement \"%s\"" % (url_rep)
  html = cgi.escape(ref_re.sub("", text))
  urls = dict(parse(ur) for ur in urls)
  if len(urls) > 0:
    pat = "|".join("(%s)" % (k)  for k in urls)
    def replace(match):
      key = match.group(0)
      return "<a href=\"%s%s\">%s</a>" % (base_wikipedia_url, urls[key], key)
    html = re.sub(pat, replace, html)
  return html

def clip_html(html, max_len):
  """
  Clips text to a maximum length while making sure not to leave invalid HTML tags.
  """
  if len(html) <= max_len:
    return html
  else:
    html = html[:max_len]
    i = html.rfind("<")
    j = html.rfind("</a>")
    k = html.rfind("<a ")
    if i > 0 and i != j:
      if i < 0 and k < 0:
        html = html[:i]
      else:
        html = html[:max(j, k)]
    html += "&hellip;"
    return html

def clip_field(event, field, html=False):
  text = event[field]
  if len(text) > max_sdb_value_len:
    event[field] = clip_html(text, max_sdb_value_len) if html else text[:max_sdb_value_len]

def prepare_event(event, min_year, year_key_digits):
  """
  Modifies an event for uploading.
  """
  event['locationText'] = [loc['text'] for loc in event['locations']]
  event['urls'] = ["%s %s" % (u, k) for k, u in event['urls'].iteritems()]
  def format_location(location):
    i, j = location.get('span') or [-1, -1]
    return "%f %f %i %i %s" % (location['latitude'], location['longitude'], i, j, location['text'])
  event['locations'] = [format_location(l) for l in event['locations']]
  event['descriptionHtml'] = make_html_description(event['description'], event.get('urls') or {})
  clip_field(event, 'description')
  clip_field(event, 'descriptionTokenized')
  clip_field(event, 'descriptionHtml', html=True)
  event['yearKey'] = dates.year_key(int(event['year']), min_year, year_key_digits)

def upload(input, dom_name, first_id, min_year, max_year, do_delete):
  sdb = boto.connect_sdb()

  year_key_digits = len(str(max_year - min_year))

  dom = None
  if do_delete:
    try:
      sdb.delete_domain(dom_name)
      print >> sys.stderr, "removing old domain"
    except boto.exception.SDBResponseError:
      print >> sys.stderr, "no old domain"
  else:
    try:
      dom = sdb.get_domain(dom_name)
      print >> sys.stderr, "using existing domain"
    except boto.exception.SDBResponseError:
      pass
  if dom is None:
    print >> sys.stderr, "creating new domain"
    dom = sdb.create_domain(dom_name)

  for i, line in enumerate(input):
    event = json.loads(line)
    print >> sys.stderr, "uploading event %i" % (i)
    prepare_event(event, min_year, year_key_digits)
    dom.put_attributes(str(i), event)

if __name__ == '__main__':
  import getopt

  try:
    opts, args = getopt.getopt(sys.argv[1:], "i:dy:")
    if len(args) not in [1, 2]:
      raise getopt.GetoptError("wrong number of positional arguments")
    opts = dict(opts)
  except getopt.GetoptError:
    print >> sys.stderr, __doc__.strip('\n\r') % (sys.argv[0])
    sys.exit(1)

  first_id = int(opts['-i']) if '-i' in opts else 0
  do_delete = '-d' in opts
  min_year, max_year = [int(y) for y in opts['-y'].split(':')] if '-y' in opts else (-1000000, 1000000)
  dom_name = args[0]
  input = open(args[1]) if len(args) > 1 else sys.stdin
  upload(input, dom_name, first_id, min_year, max_year, do_delete)
